#!/bin/bash
#
# sysjt-wrapper - part of sysjt (SYStray Job Tracker) distribution
# Copyright (C) 2011  Tieto Corp., Martin Kampas <martin.kampas@tieto.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if qdbus |grep -q '^[[:space:]]*com.tieto.sysjt$'
then
  SERVICE_AVAILABLE=true
else
  SERVICE_AVAILABLE=false
  echo "$(basename "$0"): service unavailable: com.tieto.sysjt" >&2
fi

function start_job()
{
  ${SERVICE_AVAILABLE} || return 1

  qdbus --literal com.tieto.sysjt /com/tieto/sysjt/JobManager \
    com.tieto.sysjt.JobManager.startJob "${*}" \
    |sed 's/^\[ObjectPath: \(.*\)\]/\1/'
}

function stop_job()
{
  ${SERVICE_AVAILABLE} || return 1

  local -r JOB_PATH=${1}
  local -r STATUS=${2}

  qdbus com.tieto.sysjt "${JOB_PATH}" com.tieto.sysjt.JobView.stop \
    "${STATUS}" >/dev/null
}

job_path=$(start_job "${*}")

"${@}"

retv=${?}

stop_job "${job_path}" ${retv}

exit ${retv}
